name: "Continuous Integration"
on:
  pull_request:
  push:
jobs:
  build:
    name: "Validate"
    runs-on: "ubuntu-18.04"
    steps:
      - name: "Checkout source"
        uses: "actions/checkout@v2.3.2"

      - name: "Cache for sbt & coursier"
        uses: "coursier/cache-action@v4.1"

      - name: "Install Nix"
        uses: "nixbuild/nix-quick-install-action@v2"

      - name: "sbt validate"
        run: nix-shell shell.nix --run "sbt --batch validate"
